export {default as Header} from './Component/Header/Header'
export {default as MovSir} from './Component/MovSir/MovSir'
export {default as Hero} from './Component/Home/Hero/Hero'
export {default as Scroll} from './Component/Home/Scroll/Scroll'
export {default as Footer} from './Component/Footer/Footer'
export {default as SideBar} from './Component/SideBar/SideBar'
export {default as Contact} from './Component/Contact/Contact'
export {default as GoToNextSection} from './Component/GoToNextSection/GoToNextSection'